# Neon (PostgreSQL) profile
# Activate with: SPRING_PROFILES_ACTIVE=neon
# Required env vars typically provided by Neon dashboard:
#   SPRING_DATASOURCE_URL     e.g. jdbc:postgresql://<host>:5432/<db>?sslmode=require&target_session_attrs=read-write
#   SPRING_DATASOURCE_USERNAME
#   SPRING_DATASOURCE_PASSWORD
# Notes:
# - sslmode=require is mandatory for Neon
# - target_session_attrs=read-write ensures connecting to the writable endpoint

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  tomcat:
    threads:
      max: 50

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 15000
      max-lifetime: 600000        # 10m (Neon recommends shorter lifetimes)
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate           # Prefer Flyway-managed schema
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    '[org.hibernate.SQL]': warn

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
