server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: update  # Auto-create/update schema for development
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      '[hibernate.format_sql]': true
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
      
  # H2 Console (fallback when using H2)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    '[com.codigo.LMS]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always