server:
  port: ${PORT:8080}  # Render assigns PORT environment variable
  compression:
    enabled: true
  tomcat:
    threads:
      max: 50

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}   # use the Neon URL with sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 15000
      max-lifetime: 600000        # 10m
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate           # use Flyway for schema, not auto-ddl
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    '[org.hibernate.SQL]': warn

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized